import Offer_languagesbar from '@/components/Offer-languagesbar'
import MiddleNavbar from '@/components/MiddleNavbar'
import Navbar from '@/components/Navbar'


import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Footer from '@/components/Footer';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "E-Commerce | Muhammad Arman",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Offer_languagesbar/>
        <MiddleNavbar cartCount={2}/>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
